package mysticores.lib;

public class ItemID
{
	public static int VERDITESWORD;
	public static int VERDITEPICKAXE;
	public static int VERDITESHOVEL;
	public static int VERDITEAXE;
	public static int VERDITEHOE;
	public static int MITHRILSWORD;
	public static int MITHRILPICKAXE;
	public static int MITHRILSHOVEL;
	public static int MITHRILAXE;
	public static int MITHRILHOE;
	public static int ADAMANTINESWORD;
	public static int ADAMANTINEPICKAXE;
	public static int ADAMANTINESHOVEL;
	public static int ADAMANTINEAXE;
	public static int ADAMANTINEHOE;
	public static int IRIDIUMSWORD;
	public static int IRIDIUMPICKAXE;
	public static int IRIDIUMSHOVEL;
	public static int IRIDIUMAXE;
	public static int IRIDIUMHOE;
	public static int OBSIDIANSWORD;
	public static int OBSIDIANPICKAXE;
	public static int OBSIDIANSHOVEL;
	public static int OBSIDIANAXE;
	public static int OBSIDIANHOE;
	public static int BLOODSTONESWORD;
	public static int BLOODSTONEPICKAXE;
	public static int BLOODSTONESHOVEL;
	public static int BLOODSTONEAXE;
	public static int BLOODSTONEHOE;
	public static int SATCHEL;
	public static int RESOURCES;
	
	public static int VERDITESWORD_DEFAULT = 7050;
	public static int VERDITEPICKAXE_DEFAULT = 7051;
	public static int VERDITESHOVEL_DEFAULT = 7052;
	public static int VERDITEAXE_DEFAULT = 7053;
	public static int VERDITEHOE_DEFAULT = 7054;
	public static int MITHRILSWORD_DEFAULT = 7055;
	public static int MITHRILPICKAXE_DEFAULT = 7056;
	public static int MITHRILSHOVEL_DEFAULT = 7057;
	public static int MITHRILAXE_DEFAULT = 7058;
	public static int MITHRILHOE_DEFAULT = 7059;
	public static int ADAMANTINESWORD_DEFAULT = 7060;
	public static int ADAMANTINEPICKAXE_DEFAULT = 7061;
	public static int ADAMANTINESHOVEL_DEFAULT = 7062;
	public static int ADAMANTINEAXE_DEFAULT = 7063;
	public static int ADAMANTINEHOE_DEFAULT = 7064;
	public static int IRIDIUMSWORD_DEFAULT = 7065;
	public static int IRIDIUMPICKAXE_DEFAULT = 7066;
	public static int IRIDIUMSHOVEL_DEFAULT = 7067;
	public static int IRIDIUMAXE_DEFAULT = 7068;
	public static int IRIDIUMHOE_DEFAULT = 7069;
	public static int OBSIDIANSWORD_DEFAULT = 7070;
	public static int OBSIDIANPICKAXE_DEFAULT = 7071;
	public static int OBSIDIANSHOVEL_DEFAULT = 7072;
	public static int OBSIDIANAXE_DEFAULT = 7073;
	public static int OBSIDIANHOE_DEFAULT = 7074;
	public static int BLOODSTONESWORD_DEFAULT = 7075;
	public static int BLOODSTONEPICKAXE_DEFAULT = 7076;
	public static int BLOODSTONESHOVEL_DEFAULT = 7077;
	public static int BLOODSTONEAXE_DEFAULT = 7078;
	public static int BLOODSTONEHOE_DEFAULT = 7079;
	public static int SATCHEL_DEFAULT = 7080;
	public static int RESOURCES_DEFAULT = 7081;
	
}
